# SOURCE: https://install.portworx.com/3.2?operator=true&mc=false&kbver=1.28.0&ns=portworx&b=true&iop=6&s=%22type%3DPremium_LRS%2Csize%3D150%22&mi=true&ce=azure&c=px-cluster-40ea14a4-e01b-45d0-b137-7ffb562e1776&aks=true&stork=true&csi=true&mon=true&tel=true&st=k8s&promop=true
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-40ea14a4-e01b-45d0-b137-7ffb562e1776
  namespace: portworx
  annotations:
    portworx.io/install-source: "https://install.portworx.com/3.2?operator=true&mc=false&kbver=1.28.0&ns=portworx&b=true&iop=6&s=%22type%3DPremium_LRS%2Csize%3D150%22&mi=true&ce=azure&c=px-cluster-40ea14a4-e01b-45d0-b137-7ffb562e1776&aks=true&stork=true&csi=true&mon=true&tel=true&st=k8s&promop=true"
    portworx.io/is-aks: "true"
spec:
  image: portworx/oci-monitor:3.2.2
  imagePullPolicy: Always
  kvdb:
    internal: true
  cloudStorage:
    deviceSpecs:
    - type=Premium_LRS,size=150
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  runtimeOptions:
    default-io-profile: "6"
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: true
    prometheus:
      enabled: true
      exportMetrics: true
  env:
  - name: AZURE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: px-azure
        key: AZURE_CLIENT_ID